import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { UsersDocument, useUsersQuery } from "../documents";
import { AppContext } from "next/app";
import { gql, useQuery } from "@apollo/client";
import { client } from "../graphql";

const Home: NextPage = (props) => {
  const { data } = useUsersQuery();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.jsss!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          {data?.getUsers.map((item) => {
            return (
              <a
                key={item.name}
                href="https://nextjs.org/docs"
                className={styles.card}
              >
                <h2>{item.name} &rarr;</h2>
                <p>{item.email}</p>
              </a>
            );
          })}

          {/* <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a> */}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
export async function getServerSideProps(context: AppContext) {
  const { data } = await client.query({
    query: gql`
      query Users {
        getUsers {
          name
          email
          password
        }
      }
    `,
  });
  return {
    props: { users: data }, // will be passed to the page component as props
  };
}
